# Use root/example as user/password credentials
version: '3.8'

services:
  mongo:
    image: mongo
    container_name: sfl-mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db # Mount a volume for persistent data storage
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
