# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: SFL-BACKEND=Build and deploy Node.js app to Azure Web App - sfl-backend

on:
  push:
    branches:
      - main
    paths:
      - "server-nest/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server-nest

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: server-nest
          sparse-checkout-cone-mode: false

      - name: Change directory
        run: |
          pwd
          ls -lt

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: npm install, build, and test
        run: |
          pwd
          npm install
          npm run build --if-present

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip dist/* package.json -r
          pwd
          ls -lt

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: server-nest/release.zip
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: Azure/login@v2.2.0
        with:
          client-id: ${{ secrets.SFL_BACKEND_REG_APP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SFL_BACKEND_REG_APP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B4AE9459539B4F48967F1719E417584A }}

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "sfl-backend"
          package: .
